### ISSUE TITLE
which background should be used?

### ISSUE THREAD

**Issue by seanxlliu** [kanboard/docker#2]
In the default Makefile, it seems "kanboard cronjob" to be used, however, it doesn't work in my setup.
"kanboard worker" works just as expected. 

And I saw "s6-setuidgid nginx /var/www/kanboard/kanboard worker" in services.d/worker/run, but I didn't see it is being used.

Nice job for creating the docker-compose

**Comment by seanxlliu** [comment]
Just checked the code. it seems both need to be run, correct? 

I suppose we are missing following line in the dockerfile. 
COPY files/services.d/worker /etc/services.d/worker

**Comment by fguillot** [comment]
I updated the Dockerfile, now you can use `docker-compose -f compose.alpine.postgres.beanstalk.yaml up`. These Dockerfiles are here as examples, you can customize them the way you want.

Thank you
